###################################################################################################
###                   THIS IS A REUSABLE WORKFLOW TO PUBLISH SCALA TO WINGET                    ###
### HOW TO USE:                                                                                 ###
###   - THE RELEASE WORKFLOW SHOULD CALL THIS WORKFLOW                                          ###
###   - IT WILL PUBLISH THE MSI TO WINGET                                                       ###
###                                                                                             ###
### NOTE:                                                                                       ###
###   - WE SHOULD KEEP IN SYNC THE https://github.com/dottybot/winget-pkgs REPOSITORY           ###
###################################################################################################


name: Publish Scala to winget
run-name: Publish Scala ${{ inputs.version }} to winget

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      DOTTYBOT-TOKEN:
        required: true

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@b87a066d9e624db1394edcd947f8c4e5a7e30cd7
        with:
          identifier      : Scala.Scala.3
          version         : ${{ inputs.version }}
          installers-regex: '\.msi$'
          release-tag     : ${{ inputs.version }}
          fork-user       : dottybot
          token           : ${{ secrets.DOTTYBOT-WINGET-TOKEN }}